// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
)

const countInstancesInSubnet = `-- name: CountInstancesInSubnet :one
SELECT COUNT(*) FROM instances WHERE subnet_id = ?
`

func (q *Queries) CountInstancesInSubnet(ctx context.Context, subnetID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInstancesInSubnet, subnetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSubnet = `-- name: DeleteSubnet :exec
DELETE FROM subnets WHERE id = ? AND workspace_id = ?
`

type DeleteSubnetParams struct {
	ID          string
	WorkspaceID string
}

func (q *Queries) DeleteSubnet(ctx context.Context, arg DeleteSubnetParams) error {
	_, err := q.db.ExecContext(ctx, deleteSubnet, arg.ID, arg.WorkspaceID)
	return err
}

const deleteVPC = `-- name: DeleteVPC :exec
DELETE FROM vpcs WHERE id = ? AND workspace_id = ?
`

type DeleteVPCParams struct {
	ID          string
	WorkspaceID string
}

func (q *Queries) DeleteVPC(ctx context.Context, arg DeleteVPCParams) error {
	_, err := q.db.ExecContext(ctx, deleteVPC, arg.ID, arg.WorkspaceID)
	return err
}

const eventsAfter = `-- name: EventsAfter :many
SELECT id, workspace_id, resource_type, resource_id, "action", state, generation, message, created_at FROM events WHERE id > ? ORDER BY id LIMIT ?
`

type EventsAfterParams struct {
	ID    int64
	Limit int64
}

func (q *Queries) EventsAfter(ctx context.Context, arg EventsAfterParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, eventsAfter, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ResourceType,
			&i.ResourceID,
			&i.Action,
			&i.State,
			&i.Generation,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdempotency = `-- name: GetIdempotency :one
SELECT workspace_id, operation, "key", payload_hash, resource_id, created_at, expires_at, response_json FROM idempotency_requests
WHERE workspace_id = ? AND operation = ? AND key = ?
`

type GetIdempotencyParams struct {
	WorkspaceID string
	Operation   string
	Key         string
}

func (q *Queries) GetIdempotency(ctx context.Context, arg GetIdempotencyParams) (IdempotencyRequest, error) {
	row := q.db.QueryRowContext(ctx, getIdempotency, arg.WorkspaceID, arg.Operation, arg.Key)
	var i IdempotencyRequest
	err := row.Scan(
		&i.WorkspaceID,
		&i.Operation,
		&i.Key,
		&i.PayloadHash,
		&i.ResourceID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ResponseJson,
	)
	return i, err
}

const getSubnet = `-- name: GetSubnet :one
SELECT id, workspace_id, vpc_id, short_index, name, cidr_block, availability_zone, generation, observed_generation, state, state_reason, created_at, updated_at FROM subnets WHERE id = ? AND workspace_id = ?
`

type GetSubnetParams struct {
	ID          string
	WorkspaceID string
}

func (q *Queries) GetSubnet(ctx context.Context, arg GetSubnetParams) (Subnet, error) {
	row := q.db.QueryRowContext(ctx, getSubnet, arg.ID, arg.WorkspaceID)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.VpcID,
		&i.ShortIndex,
		&i.Name,
		&i.CidrBlock,
		&i.AvailabilityZone,
		&i.Generation,
		&i.ObservedGeneration,
		&i.State,
		&i.StateReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubnetByName = `-- name: GetSubnetByName :one
SELECT id, workspace_id, vpc_id, short_index, name, cidr_block, availability_zone, generation, observed_generation, state, state_reason, created_at, updated_at FROM subnets WHERE workspace_id = ? AND name = ?
`

type GetSubnetByNameParams struct {
	WorkspaceID string
	Name        string
}

func (q *Queries) GetSubnetByName(ctx context.Context, arg GetSubnetByNameParams) (Subnet, error) {
	row := q.db.QueryRowContext(ctx, getSubnetByName, arg.WorkspaceID, arg.Name)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.VpcID,
		&i.ShortIndex,
		&i.Name,
		&i.CidrBlock,
		&i.AvailabilityZone,
		&i.Generation,
		&i.ObservedGeneration,
		&i.State,
		&i.StateReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVPC = `-- name: GetVPC :one
SELECT id, workspace_id, short_index, name, cidr_block, generation, observed_generation, state, state_reason, created_at, updated_at FROM vpcs WHERE id = ? AND workspace_id = ?
`

type GetVPCParams struct {
	ID          string
	WorkspaceID string
}

func (q *Queries) GetVPC(ctx context.Context, arg GetVPCParams) (Vpc, error) {
	row := q.db.QueryRowContext(ctx, getVPC, arg.ID, arg.WorkspaceID)
	var i Vpc
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ShortIndex,
		&i.Name,
		&i.CidrBlock,
		&i.Generation,
		&i.ObservedGeneration,
		&i.State,
		&i.StateReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVPCByName = `-- name: GetVPCByName :one
SELECT id, workspace_id, short_index, name, cidr_block, generation, observed_generation, state, state_reason, created_at, updated_at FROM vpcs WHERE workspace_id = ? AND name = ?
`

type GetVPCByNameParams struct {
	WorkspaceID string
	Name        string
}

func (q *Queries) GetVPCByName(ctx context.Context, arg GetVPCByNameParams) (Vpc, error) {
	row := q.db.QueryRowContext(ctx, getVPCByName, arg.WorkspaceID, arg.Name)
	var i Vpc
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ShortIndex,
		&i.Name,
		&i.CidrBlock,
		&i.Generation,
		&i.ObservedGeneration,
		&i.State,
		&i.StateReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (
    workspace_id, resource_type, resource_id, action, state, generation,
    created_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	WorkspaceID  string
	ResourceType string
	ResourceID   string
	Action       string
	State        string
	Generation   int64
	CreatedAt    int64
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.WorkspaceID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Action,
		arg.State,
		arg.Generation,
		arg.CreatedAt,
	)
	return err
}

const insertSubnet = `-- name: InsertSubnet :exec
INSERT INTO subnets (
    id, workspace_id, vpc_id, short_index, name, cidr_block,
    availability_zone, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSubnetParams struct {
	ID               string
	WorkspaceID      string
	VpcID            string
	ShortIndex       int64
	Name             string
	CidrBlock        string
	AvailabilityZone string
	CreatedAt        int64
	UpdatedAt        int64
}

func (q *Queries) InsertSubnet(ctx context.Context, arg InsertSubnetParams) error {
	_, err := q.db.ExecContext(ctx, insertSubnet,
		arg.ID,
		arg.WorkspaceID,
		arg.VpcID,
		arg.ShortIndex,
		arg.Name,
		arg.CidrBlock,
		arg.AvailabilityZone,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertVPC = `-- name: InsertVPC :exec
INSERT INTO vpcs (
    id, workspace_id, short_index, name, cidr_block, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertVPCParams struct {
	ID          string
	WorkspaceID string
	ShortIndex  int64
	Name        string
	CidrBlock   string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) InsertVPC(ctx context.Context, arg InsertVPCParams) error {
	_, err := q.db.ExecContext(ctx, insertVPC,
		arg.ID,
		arg.WorkspaceID,
		arg.ShortIndex,
		arg.Name,
		arg.CidrBlock,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listSubnetPage = `-- name: ListSubnetPage :many
SELECT id, workspace_id, vpc_id, short_index, name, cidr_block, availability_zone, generation, observed_generation, state, state_reason, created_at, updated_at FROM subnets
WHERE workspace_id = ? AND id > ?
ORDER BY id
LIMIT ?
`

type ListSubnetPageParams struct {
	WorkspaceID string
	ID          string
	Limit       int64
}

func (q *Queries) ListSubnetPage(ctx context.Context, arg ListSubnetPageParams) ([]Subnet, error) {
	rows, err := q.db.QueryContext(ctx, listSubnetPage, arg.WorkspaceID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subnet
	for rows.Next() {
		var i Subnet
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.VpcID,
			&i.ShortIndex,
			&i.Name,
			&i.CidrBlock,
			&i.AvailabilityZone,
			&i.Generation,
			&i.ObservedGeneration,
			&i.State,
			&i.StateReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubnetsByVPC = `-- name: ListSubnetsByVPC :many
SELECT id, workspace_id, vpc_id, short_index, name, cidr_block, availability_zone, generation, observed_generation, state, state_reason, created_at, updated_at FROM subnets WHERE vpc_id = ? ORDER BY id
`

func (q *Queries) ListSubnetsByVPC(ctx context.Context, vpcID string) ([]Subnet, error) {
	rows, err := q.db.QueryContext(ctx, listSubnetsByVPC, vpcID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subnet
	for rows.Next() {
		var i Subnet
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.VpcID,
			&i.ShortIndex,
			&i.Name,
			&i.CidrBlock,
			&i.AvailabilityZone,
			&i.Generation,
			&i.ObservedGeneration,
			&i.State,
			&i.StateReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVPCPage = `-- name: ListVPCPage :many
SELECT id, workspace_id, short_index, name, cidr_block, generation, observed_generation, state, state_reason, created_at, updated_at FROM vpcs
WHERE workspace_id = ? AND id > ?
ORDER BY id
LIMIT ?
`

type ListVPCPageParams struct {
	WorkspaceID string
	ID          string
	Limit       int64
}

func (q *Queries) ListVPCPage(ctx context.Context, arg ListVPCPageParams) ([]Vpc, error) {
	rows, err := q.db.QueryContext(ctx, listVPCPage, arg.WorkspaceID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vpc
	for rows.Next() {
		var i Vpc
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ShortIndex,
			&i.Name,
			&i.CidrBlock,
			&i.Generation,
			&i.ObservedGeneration,
			&i.State,
			&i.StateReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubnetDeleting = `-- name: MarkSubnetDeleting :exec
UPDATE subnets SET state = 'deleting', state_reason = '',
    generation = generation + 1, updated_at = ?
WHERE id = ? AND workspace_id = ? AND state != 'deleting'
`

type MarkSubnetDeletingParams struct {
	UpdatedAt   int64
	ID          string
	WorkspaceID string
}

func (q *Queries) MarkSubnetDeleting(ctx context.Context, arg MarkSubnetDeletingParams) error {
	_, err := q.db.ExecContext(ctx, markSubnetDeleting, arg.UpdatedAt, arg.ID, arg.WorkspaceID)
	return err
}

const markVPCDeleting = `-- name: MarkVPCDeleting :exec
UPDATE vpcs SET state = 'deleting', state_reason = '',
    generation = generation + 1, updated_at = ?
WHERE id = ? AND workspace_id = ? AND state != 'deleting'
`

type MarkVPCDeletingParams struct {
	UpdatedAt   int64
	ID          string
	WorkspaceID string
}

func (q *Queries) MarkVPCDeleting(ctx context.Context, arg MarkVPCDeletingParams) error {
	_, err := q.db.ExecContext(ctx, markVPCDeleting, arg.UpdatedAt, arg.ID, arg.WorkspaceID)
	return err
}

const putIdempotency = `-- name: PutIdempotency :exec
INSERT INTO idempotency_requests (
    workspace_id, operation, key, payload_hash, resource_id, response_json, created_at, expires_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(workspace_id, operation, key) DO UPDATE SET
    payload_hash = excluded.payload_hash,
    resource_id = excluded.resource_id,
    response_json = excluded.response_json,
    created_at = excluded.created_at,
    expires_at = excluded.expires_at
`

type PutIdempotencyParams struct {
	WorkspaceID  string
	Operation    string
	Key          string
	PayloadHash  string
	ResourceID   string
	ResponseJson string
	CreatedAt    int64
	ExpiresAt    int64
}

func (q *Queries) PutIdempotency(ctx context.Context, arg PutIdempotencyParams) error {
	_, err := q.db.ExecContext(ctx, putIdempotency,
		arg.WorkspaceID,
		arg.Operation,
		arg.Key,
		arg.PayloadHash,
		arg.ResourceID,
		arg.ResponseJson,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const updateSubnetStatus = `-- name: UpdateSubnetStatus :exec
UPDATE subnets
SET state = ?, state_reason = ?, observed_generation = ?, updated_at = ?
WHERE id = ? AND workspace_id = ?
`

type UpdateSubnetStatusParams struct {
	State              string
	StateReason        string
	ObservedGeneration int64
	UpdatedAt          int64
	ID                 string
	WorkspaceID        string
}

func (q *Queries) UpdateSubnetStatus(ctx context.Context, arg UpdateSubnetStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSubnetStatus,
		arg.State,
		arg.StateReason,
		arg.ObservedGeneration,
		arg.UpdatedAt,
		arg.ID,
		arg.WorkspaceID,
	)
	return err
}

const updateVPCStatus = `-- name: UpdateVPCStatus :exec
UPDATE vpcs
SET state = ?, state_reason = ?, observed_generation = ?, updated_at = ?
WHERE id = ? AND workspace_id = ?
`

type UpdateVPCStatusParams struct {
	State              string
	StateReason        string
	ObservedGeneration int64
	UpdatedAt          int64
	ID                 string
	WorkspaceID        string
}

func (q *Queries) UpdateVPCStatus(ctx context.Context, arg UpdateVPCStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateVPCStatus,
		arg.State,
		arg.StateReason,
		arg.ObservedGeneration,
		arg.UpdatedAt,
		arg.ID,
		arg.WorkspaceID,
	)
	return err
}
