// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countInstancesInSubnet = `-- name: CountInstancesInSubnet :one
SELECT COUNT(*) FROM instances WHERE subnet_id = ?
`

func (q *Queries) CountInstancesInSubnet(ctx context.Context, subnetID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInstancesInSubnet, subnetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteInstance = `-- name: DeleteInstance :exec
DELETE FROM instances WHERE id = ? AND workspace_id = ?
`

type DeleteInstanceParams struct {
	ID          string
	WorkspaceID string
}

func (q *Queries) DeleteInstance(ctx context.Context, arg DeleteInstanceParams) error {
	_, err := q.db.ExecContext(ctx, deleteInstance, arg.ID, arg.WorkspaceID)
	return err
}

const deleteInstanceENI = `-- name: DeleteInstanceENI :exec
DELETE FROM enis WHERE id = ? AND workspace_id = ?
`

type DeleteInstanceENIParams struct {
	ID          string
	WorkspaceID string
}

func (q *Queries) DeleteInstanceENI(ctx context.Context, arg DeleteInstanceENIParams) error {
	_, err := q.db.ExecContext(ctx, deleteInstanceENI, arg.ID, arg.WorkspaceID)
	return err
}

const deleteSubnet = `-- name: DeleteSubnet :exec
DELETE FROM subnets WHERE id = ? AND workspace_id = ?
`

type DeleteSubnetParams struct {
	ID          string
	WorkspaceID string
}

func (q *Queries) DeleteSubnet(ctx context.Context, arg DeleteSubnetParams) error {
	_, err := q.db.ExecContext(ctx, deleteSubnet, arg.ID, arg.WorkspaceID)
	return err
}

const deleteVPC = `-- name: DeleteVPC :exec
DELETE FROM vpcs WHERE id = ? AND workspace_id = ?
`

type DeleteVPCParams struct {
	ID          string
	WorkspaceID string
}

func (q *Queries) DeleteVPC(ctx context.Context, arg DeleteVPCParams) error {
	_, err := q.db.ExecContext(ctx, deleteVPC, arg.ID, arg.WorkspaceID)
	return err
}

const eventsAfter = `-- name: EventsAfter :many
SELECT id, workspace_id, resource_type, resource_id, "action", state, generation, message, created_at FROM events WHERE id > ? ORDER BY id LIMIT ?
`

type EventsAfterParams struct {
	ID    int64
	Limit int64
}

func (q *Queries) EventsAfter(ctx context.Context, arg EventsAfterParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, eventsAfter, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ResourceType,
			&i.ResourceID,
			&i.Action,
			&i.State,
			&i.Generation,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdempotency = `-- name: GetIdempotency :one
SELECT workspace_id, operation, "key", payload_hash, resource_id, created_at, expires_at, response_json FROM idempotency_requests
WHERE workspace_id = ? AND operation = ? AND key = ?
`

type GetIdempotencyParams struct {
	WorkspaceID string
	Operation   string
	Key         string
}

func (q *Queries) GetIdempotency(ctx context.Context, arg GetIdempotencyParams) (IdempotencyRequest, error) {
	row := q.db.QueryRowContext(ctx, getIdempotency, arg.WorkspaceID, arg.Operation, arg.Key)
	var i IdempotencyRequest
	err := row.Scan(
		&i.WorkspaceID,
		&i.Operation,
		&i.Key,
		&i.PayloadHash,
		&i.ResourceID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ResponseJson,
	)
	return i, err
}

const getInstance = `-- name: GetInstance :one
SELECT id, workspace_id, subnet_id, short_index, name, generation, observed_generation, state, state_reason, created_at, updated_at, deletion_requested, runtime_id FROM instances WHERE id = ? AND workspace_id = ?
`

type GetInstanceParams struct {
	ID          string
	WorkspaceID string
}

func (q *Queries) GetInstance(ctx context.Context, arg GetInstanceParams) (Instance, error) {
	row := q.db.QueryRowContext(ctx, getInstance, arg.ID, arg.WorkspaceID)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SubnetID,
		&i.ShortIndex,
		&i.Name,
		&i.Generation,
		&i.ObservedGeneration,
		&i.State,
		&i.StateReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionRequested,
		&i.RuntimeID,
	)
	return i, err
}

const getInstanceByName = `-- name: GetInstanceByName :one
SELECT id, workspace_id, subnet_id, short_index, name, generation, observed_generation, state, state_reason, created_at, updated_at, deletion_requested, runtime_id FROM instances WHERE workspace_id = ? AND name = ?
`

type GetInstanceByNameParams struct {
	WorkspaceID string
	Name        string
}

func (q *Queries) GetInstanceByName(ctx context.Context, arg GetInstanceByNameParams) (Instance, error) {
	row := q.db.QueryRowContext(ctx, getInstanceByName, arg.WorkspaceID, arg.Name)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SubnetID,
		&i.ShortIndex,
		&i.Name,
		&i.Generation,
		&i.ObservedGeneration,
		&i.State,
		&i.StateReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionRequested,
		&i.RuntimeID,
	)
	return i, err
}

const getPrimaryENI = `-- name: GetPrimaryENI :one
SELECT id, workspace_id, instance_id, subnet_id, short_index, private_ip, mac_address, generation, observed_generation, state, state_reason, created_at, updated_at FROM enis WHERE instance_id = ? AND workspace_id = ?
`

type GetPrimaryENIParams struct {
	InstanceID  string
	WorkspaceID string
}

func (q *Queries) GetPrimaryENI(ctx context.Context, arg GetPrimaryENIParams) (Eni, error) {
	row := q.db.QueryRowContext(ctx, getPrimaryENI, arg.InstanceID, arg.WorkspaceID)
	var i Eni
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InstanceID,
		&i.SubnetID,
		&i.ShortIndex,
		&i.PrivateIp,
		&i.MacAddress,
		&i.Generation,
		&i.ObservedGeneration,
		&i.State,
		&i.StateReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubnet = `-- name: GetSubnet :one
SELECT id, workspace_id, vpc_id, short_index, name, cidr_block, availability_zone, generation, observed_generation, state, state_reason, created_at, updated_at, deletion_requested FROM subnets WHERE id = ? AND workspace_id = ?
`

type GetSubnetParams struct {
	ID          string
	WorkspaceID string
}

func (q *Queries) GetSubnet(ctx context.Context, arg GetSubnetParams) (Subnet, error) {
	row := q.db.QueryRowContext(ctx, getSubnet, arg.ID, arg.WorkspaceID)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.VpcID,
		&i.ShortIndex,
		&i.Name,
		&i.CidrBlock,
		&i.AvailabilityZone,
		&i.Generation,
		&i.ObservedGeneration,
		&i.State,
		&i.StateReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionRequested,
	)
	return i, err
}

const getSubnetByName = `-- name: GetSubnetByName :one
SELECT id, workspace_id, vpc_id, short_index, name, cidr_block, availability_zone, generation, observed_generation, state, state_reason, created_at, updated_at, deletion_requested FROM subnets WHERE workspace_id = ? AND name = ?
`

type GetSubnetByNameParams struct {
	WorkspaceID string
	Name        string
}

func (q *Queries) GetSubnetByName(ctx context.Context, arg GetSubnetByNameParams) (Subnet, error) {
	row := q.db.QueryRowContext(ctx, getSubnetByName, arg.WorkspaceID, arg.Name)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.VpcID,
		&i.ShortIndex,
		&i.Name,
		&i.CidrBlock,
		&i.AvailabilityZone,
		&i.Generation,
		&i.ObservedGeneration,
		&i.State,
		&i.StateReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionRequested,
	)
	return i, err
}

const getVPC = `-- name: GetVPC :one
SELECT id, workspace_id, short_index, name, cidr_block, generation, observed_generation, state, state_reason, created_at, updated_at, deletion_requested FROM vpcs WHERE id = ? AND workspace_id = ?
`

type GetVPCParams struct {
	ID          string
	WorkspaceID string
}

func (q *Queries) GetVPC(ctx context.Context, arg GetVPCParams) (Vpc, error) {
	row := q.db.QueryRowContext(ctx, getVPC, arg.ID, arg.WorkspaceID)
	var i Vpc
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ShortIndex,
		&i.Name,
		&i.CidrBlock,
		&i.Generation,
		&i.ObservedGeneration,
		&i.State,
		&i.StateReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionRequested,
	)
	return i, err
}

const getVPCByName = `-- name: GetVPCByName :one
SELECT id, workspace_id, short_index, name, cidr_block, generation, observed_generation, state, state_reason, created_at, updated_at, deletion_requested FROM vpcs WHERE workspace_id = ? AND name = ?
`

type GetVPCByNameParams struct {
	WorkspaceID string
	Name        string
}

func (q *Queries) GetVPCByName(ctx context.Context, arg GetVPCByNameParams) (Vpc, error) {
	row := q.db.QueryRowContext(ctx, getVPCByName, arg.WorkspaceID, arg.Name)
	var i Vpc
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ShortIndex,
		&i.Name,
		&i.CidrBlock,
		&i.Generation,
		&i.ObservedGeneration,
		&i.State,
		&i.StateReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionRequested,
	)
	return i, err
}

const insertENI = `-- name: InsertENI :exec
INSERT INTO enis(id, workspace_id, instance_id, subnet_id, short_index, private_ip, mac_address, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertENIParams struct {
	ID          string
	WorkspaceID string
	InstanceID  string
	SubnetID    string
	ShortIndex  int64
	PrivateIp   string
	MacAddress  string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) InsertENI(ctx context.Context, arg InsertENIParams) error {
	_, err := q.db.ExecContext(ctx, insertENI,
		arg.ID,
		arg.WorkspaceID,
		arg.InstanceID,
		arg.SubnetID,
		arg.ShortIndex,
		arg.PrivateIp,
		arg.MacAddress,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (
    workspace_id, resource_type, resource_id, action, state, generation,
    message, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	WorkspaceID  string
	ResourceType string
	ResourceID   string
	Action       string
	State        string
	Generation   int64
	Message      string
	CreatedAt    int64
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.WorkspaceID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Action,
		arg.State,
		arg.Generation,
		arg.Message,
		arg.CreatedAt,
	)
	return err
}

const insertInstance = `-- name: InsertInstance :exec
INSERT INTO instances(id, workspace_id, subnet_id, short_index, name, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertInstanceParams struct {
	ID          string
	WorkspaceID string
	SubnetID    string
	ShortIndex  int64
	Name        string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) InsertInstance(ctx context.Context, arg InsertInstanceParams) error {
	_, err := q.db.ExecContext(ctx, insertInstance,
		arg.ID,
		arg.WorkspaceID,
		arg.SubnetID,
		arg.ShortIndex,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertSubnet = `-- name: InsertSubnet :exec
INSERT INTO subnets (
    id, workspace_id, vpc_id, short_index, name, cidr_block,
    availability_zone, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSubnetParams struct {
	ID               string
	WorkspaceID      string
	VpcID            string
	ShortIndex       int64
	Name             string
	CidrBlock        string
	AvailabilityZone string
	CreatedAt        int64
	UpdatedAt        int64
}

func (q *Queries) InsertSubnet(ctx context.Context, arg InsertSubnetParams) error {
	_, err := q.db.ExecContext(ctx, insertSubnet,
		arg.ID,
		arg.WorkspaceID,
		arg.VpcID,
		arg.ShortIndex,
		arg.Name,
		arg.CidrBlock,
		arg.AvailabilityZone,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertVPC = `-- name: InsertVPC :exec
INSERT INTO vpcs (
    id, workspace_id, short_index, name, cidr_block, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertVPCParams struct {
	ID          string
	WorkspaceID string
	ShortIndex  int64
	Name        string
	CidrBlock   string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) InsertVPC(ctx context.Context, arg InsertVPCParams) error {
	_, err := q.db.ExecContext(ctx, insertVPC,
		arg.ID,
		arg.WorkspaceID,
		arg.ShortIndex,
		arg.Name,
		arg.CidrBlock,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listENIAddresses = `-- name: ListENIAddresses :many
SELECT private_ip FROM enis WHERE subnet_id = ? ORDER BY private_ip
`

func (q *Queries) ListENIAddresses(ctx context.Context, subnetID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listENIAddresses, subnetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var private_ip string
		if err := rows.Scan(&private_ip); err != nil {
			return nil, err
		}
		items = append(items, private_ip)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstancePage = `-- name: ListInstancePage :many
SELECT id, workspace_id, subnet_id, short_index, name, generation, observed_generation, state, state_reason, created_at, updated_at, deletion_requested, runtime_id FROM instances WHERE workspace_id = ? AND id > ? ORDER BY id LIMIT ?
`

type ListInstancePageParams struct {
	WorkspaceID string
	ID          string
	Limit       int64
}

func (q *Queries) ListInstancePage(ctx context.Context, arg ListInstancePageParams) ([]Instance, error) {
	rows, err := q.db.QueryContext(ctx, listInstancePage, arg.WorkspaceID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SubnetID,
			&i.ShortIndex,
			&i.Name,
			&i.Generation,
			&i.ObservedGeneration,
			&i.State,
			&i.StateReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletionRequested,
			&i.RuntimeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubnetPage = `-- name: ListSubnetPage :many
SELECT id, workspace_id, vpc_id, short_index, name, cidr_block, availability_zone, generation, observed_generation, state, state_reason, created_at, updated_at, deletion_requested FROM subnets
WHERE workspace_id = ? AND id > ?
ORDER BY id
LIMIT ?
`

type ListSubnetPageParams struct {
	WorkspaceID string
	ID          string
	Limit       int64
}

func (q *Queries) ListSubnetPage(ctx context.Context, arg ListSubnetPageParams) ([]Subnet, error) {
	rows, err := q.db.QueryContext(ctx, listSubnetPage, arg.WorkspaceID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subnet
	for rows.Next() {
		var i Subnet
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.VpcID,
			&i.ShortIndex,
			&i.Name,
			&i.CidrBlock,
			&i.AvailabilityZone,
			&i.Generation,
			&i.ObservedGeneration,
			&i.State,
			&i.StateReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletionRequested,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubnetsByVPC = `-- name: ListSubnetsByVPC :many
SELECT id, workspace_id, vpc_id, short_index, name, cidr_block, availability_zone, generation, observed_generation, state, state_reason, created_at, updated_at, deletion_requested FROM subnets WHERE vpc_id = ? ORDER BY id
`

func (q *Queries) ListSubnetsByVPC(ctx context.Context, vpcID string) ([]Subnet, error) {
	rows, err := q.db.QueryContext(ctx, listSubnetsByVPC, vpcID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subnet
	for rows.Next() {
		var i Subnet
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.VpcID,
			&i.ShortIndex,
			&i.Name,
			&i.CidrBlock,
			&i.AvailabilityZone,
			&i.Generation,
			&i.ObservedGeneration,
			&i.State,
			&i.StateReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletionRequested,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVPCPage = `-- name: ListVPCPage :many
SELECT id, workspace_id, short_index, name, cidr_block, generation, observed_generation, state, state_reason, created_at, updated_at, deletion_requested FROM vpcs
WHERE workspace_id = ? AND id > ?
ORDER BY id
LIMIT ?
`

type ListVPCPageParams struct {
	WorkspaceID string
	ID          string
	Limit       int64
}

func (q *Queries) ListVPCPage(ctx context.Context, arg ListVPCPageParams) ([]Vpc, error) {
	rows, err := q.db.QueryContext(ctx, listVPCPage, arg.WorkspaceID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vpc
	for rows.Next() {
		var i Vpc
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ShortIndex,
			&i.Name,
			&i.CidrBlock,
			&i.Generation,
			&i.ObservedGeneration,
			&i.State,
			&i.StateReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletionRequested,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInstanceTerminating = `-- name: MarkInstanceTerminating :exec
UPDATE instances SET state = 'shutting-down', state_reason = '', deletion_requested = 1,
    generation = generation + 1, updated_at = ?
WHERE id = ? AND workspace_id = ? AND deletion_requested = 0
`

type MarkInstanceTerminatingParams struct {
	UpdatedAt   int64
	ID          string
	WorkspaceID string
}

func (q *Queries) MarkInstanceTerminating(ctx context.Context, arg MarkInstanceTerminatingParams) error {
	_, err := q.db.ExecContext(ctx, markInstanceTerminating, arg.UpdatedAt, arg.ID, arg.WorkspaceID)
	return err
}

const markSubnetDeleting = `-- name: MarkSubnetDeleting :exec
UPDATE subnets SET state = 'deleting', state_reason = '', deletion_requested = 1,
    generation = generation + 1, updated_at = ?
WHERE id = ? AND workspace_id = ? AND deletion_requested = 0
`

type MarkSubnetDeletingParams struct {
	UpdatedAt   int64
	ID          string
	WorkspaceID string
}

func (q *Queries) MarkSubnetDeleting(ctx context.Context, arg MarkSubnetDeletingParams) error {
	_, err := q.db.ExecContext(ctx, markSubnetDeleting, arg.UpdatedAt, arg.ID, arg.WorkspaceID)
	return err
}

const markVPCDeleting = `-- name: MarkVPCDeleting :exec
UPDATE vpcs SET state = 'deleting', state_reason = '', deletion_requested = 1,
    generation = generation + 1, updated_at = ?
WHERE id = ? AND workspace_id = ? AND deletion_requested = 0
`

type MarkVPCDeletingParams struct {
	UpdatedAt   int64
	ID          string
	WorkspaceID string
}

func (q *Queries) MarkVPCDeleting(ctx context.Context, arg MarkVPCDeletingParams) error {
	_, err := q.db.ExecContext(ctx, markVPCDeleting, arg.UpdatedAt, arg.ID, arg.WorkspaceID)
	return err
}

const putIdempotency = `-- name: PutIdempotency :exec
INSERT INTO idempotency_requests (
    workspace_id, operation, key, payload_hash, resource_id, response_json, created_at, expires_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(workspace_id, operation, key) DO UPDATE SET
    payload_hash = excluded.payload_hash,
    resource_id = excluded.resource_id,
    response_json = excluded.response_json,
    created_at = excluded.created_at,
    expires_at = excluded.expires_at
`

type PutIdempotencyParams struct {
	WorkspaceID  string
	Operation    string
	Key          string
	PayloadHash  string
	ResourceID   string
	ResponseJson string
	CreatedAt    int64
	ExpiresAt    int64
}

func (q *Queries) PutIdempotency(ctx context.Context, arg PutIdempotencyParams) error {
	_, err := q.db.ExecContext(ctx, putIdempotency,
		arg.WorkspaceID,
		arg.Operation,
		arg.Key,
		arg.PayloadHash,
		arg.ResourceID,
		arg.ResponseJson,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const recordRuntimeID = `-- name: RecordRuntimeID :execrows
UPDATE instances SET runtime_id = ?
WHERE id = ? AND generation = ? AND deletion_requested = 0
    AND (runtime_id IS NULL OR runtime_id = ?)
`

type RecordRuntimeIDParams struct {
	RuntimeID   sql.NullString
	ID          string
	Generation  int64
	RuntimeID_2 sql.NullString
}

func (q *Queries) RecordRuntimeID(ctx context.Context, arg RecordRuntimeIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordRuntimeID,
		arg.RuntimeID,
		arg.ID,
		arg.Generation,
		arg.RuntimeID_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retainTerminatingRuntimeID = `-- name: RetainTerminatingRuntimeID :execrows
UPDATE instances SET runtime_id = ?
WHERE id = ? AND deletion_requested = 1 AND runtime_id IS NULL
`

type RetainTerminatingRuntimeIDParams struct {
	RuntimeID sql.NullString
	ID        string
}

func (q *Queries) RetainTerminatingRuntimeID(ctx context.Context, arg RetainTerminatingRuntimeIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, retainTerminatingRuntimeID, arg.RuntimeID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateInstanceENIStatus = `-- name: UpdateInstanceENIStatus :exec
UPDATE enis SET state = ?, state_reason = ?, observed_generation = ?, updated_at = ?
WHERE id = ? AND workspace_id = ?
`

type UpdateInstanceENIStatusParams struct {
	State              string
	StateReason        string
	ObservedGeneration int64
	UpdatedAt          int64
	ID                 string
	WorkspaceID        string
}

func (q *Queries) UpdateInstanceENIStatus(ctx context.Context, arg UpdateInstanceENIStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateInstanceENIStatus,
		arg.State,
		arg.StateReason,
		arg.ObservedGeneration,
		arg.UpdatedAt,
		arg.ID,
		arg.WorkspaceID,
	)
	return err
}

const updateInstanceStatus = `-- name: UpdateInstanceStatus :exec
UPDATE instances SET state = ?, state_reason = ?, observed_generation = ?, updated_at = ?
WHERE id = ? AND workspace_id = ?
`

type UpdateInstanceStatusParams struct {
	State              string
	StateReason        string
	ObservedGeneration int64
	UpdatedAt          int64
	ID                 string
	WorkspaceID        string
}

func (q *Queries) UpdateInstanceStatus(ctx context.Context, arg UpdateInstanceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateInstanceStatus,
		arg.State,
		arg.StateReason,
		arg.ObservedGeneration,
		arg.UpdatedAt,
		arg.ID,
		arg.WorkspaceID,
	)
	return err
}

const updateSubnetStatus = `-- name: UpdateSubnetStatus :exec
UPDATE subnets
SET state = ?, state_reason = ?, observed_generation = ?, updated_at = ?
WHERE id = ? AND workspace_id = ?
`

type UpdateSubnetStatusParams struct {
	State              string
	StateReason        string
	ObservedGeneration int64
	UpdatedAt          int64
	ID                 string
	WorkspaceID        string
}

func (q *Queries) UpdateSubnetStatus(ctx context.Context, arg UpdateSubnetStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSubnetStatus,
		arg.State,
		arg.StateReason,
		arg.ObservedGeneration,
		arg.UpdatedAt,
		arg.ID,
		arg.WorkspaceID,
	)
	return err
}

const updateVPCStatus = `-- name: UpdateVPCStatus :exec
UPDATE vpcs
SET state = ?, state_reason = ?, observed_generation = ?, updated_at = ?
WHERE id = ? AND workspace_id = ?
`

type UpdateVPCStatusParams struct {
	State              string
	StateReason        string
	ObservedGeneration int64
	UpdatedAt          int64
	ID                 string
	WorkspaceID        string
}

func (q *Queries) UpdateVPCStatus(ctx context.Context, arg UpdateVPCStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateVPCStatus,
		arg.State,
		arg.StateReason,
		arg.ObservedGeneration,
		arg.UpdatedAt,
		arg.ID,
		arg.WorkspaceID,
	)
	return err
}
